trigger:
  - main

schedules:
  - cron: "30 4 * * 1,3,5"   # 10:00 AM IST = 4:30 AM UTC
    displayName: "Scheduled Trigger: Mon/Wed/Fri 10:00 AM IST"
    branches:
      include:
        - main
    always: true

pool:
  vmImage: 'windows-latest'

variables:
  - name: ALLURE_VERSION
    value: '2.25.0'
  - name: system.debug
    value: false
  - name: RUNNING_IN_PIPELINE
    value: 'true'

steps:
- checkout: self
  fetchDepth: 1
  displayName: 'Checkout Code'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'
    addToPath: true
  displayName: 'Setup Python'

- powershell: |
    Write-Host "Installing Python dependencies..."
    python -m pip install --upgrade pip
    python -m pip install -r requirements.txt
    python -m pip install allure-pytest pytest requests webdriver-manager
    Write-Host "Installed packages:"
    python -m pip list | Select-String -Pattern "(pytest|allure|selenium|webdriver)"
  displayName: 'Install Python Dependencies'

- powershell: |
    Write-Host "Installing Chrome browser..."
    # Chrome is already installed on Windows Azure agents
    # Check if Chrome is available
    $chromePath = Get-Command chrome -ErrorAction SilentlyContinue
    if ($chromePath) {
        Write-Host "Chrome already available at: $($chromePath.Source)"
        & chrome --version
    } else {
        Write-Host "Installing Chrome via Chocolatey..."
        choco install googlechrome -y
        Write-Host "Chrome installation completed"
    }
  displayName: 'Setup Chrome Browser'

- powershell: |
    Write-Host "Setting up test environment for Windows..."
    # Windows doesn't need virtual display setup
    # Set environment variables for pipeline
    $env:RUNNING_IN_PIPELINE = "true"
    $env:PYTEST_CURRENT_TEST = ""
    Write-Host "Environment variables set for pipeline execution"
  displayName: 'Setup Test Environment'

- powershell: |
    Write-Host "Setting up test execution..."
    if (!(Test-Path "allure-results")) {
        New-Item -ItemType Directory -Name "allure-results"
    }
    
    # Set environment variables
    $env:RUNNING_IN_PIPELINE = "true"
    $env:PYTEST_CURRENT_TEST = ""
    
    Write-Host "Checking test discovery..."
    python -m pytest --collect-only tests/ | Select-Object -First 20
    Write-Host "Total tests discovered:"
    $collectOutput = python -m pytest --collect-only tests/ -q 2>&1
    if ($collectOutput -match "test session starts") {
        Write-Host $collectOutput
    } else {
        Write-Host "No tests discovered or collection failed"
    }
    
    Write-Host "Running tests with comprehensive logging..."
    $pytestArgs = @(
        "tests/",
        "--alluredir=allure-results",
        "--clean-alluredir",
        "-v",
        "--tb=short",
        "--maxfail=5",
        "--capture=no",
        "--log-cli-level=INFO"
    )
    
    python -m pytest @pytestArgs
    $PYTEST_EXIT_CODE = $LASTEXITCODE
    Write-Host "Pytest completed with exit code: $PYTEST_EXIT_CODE"
    
    Write-Host "Checking allure-results..."
    if (Test-Path "allure-results") {
        Write-Host "Contents of allure-results:"
        Get-ChildItem "allure-results" | Select-Object -First 10
        $jsonFiles = Get-ChildItem "allure-results" -Filter "*.json"
        $JSON_COUNT = $jsonFiles.Count
        Write-Host "Total JSON result files: $JSON_COUNT"
        
        if ($JSON_COUNT -eq 0) {
            Write-Host "WARNING: No Allure result files generated!"
            Write-Host "Creating minimal test result for report generation..."
            $minimalResult = @{
                uuid = "minimal-test-result"
                name = "Pipeline Test Discovery"
                fullName = "pipeline.test_discovery"
                status = "failed"
                statusDetails = @{
                    message = "Tests failed to execute in pipeline environment"
                    trace = "Check pipeline logs for WebDriver or import errors"
                }
                stage = "finished"
                start = 1640995200000
                stop = 1640995260000
                labels = @(
                    @{ name = "suite"; value = "Pipeline Diagnostics" },
                    @{ name = "framework"; value = "pytest" }
                )
            }
            $minimalResult | ConvertTo-Json -Depth 10 | Out-File -FilePath "allure-results/minimal-result.json" -Encoding UTF8
            Write-Host "Minimal result file created for debugging"
        }
    } else {
        Write-Host "ERROR: allure-results directory missing!"
        New-Item -ItemType Directory -Name "allure-results"
    }
  displayName: 'Run Pytest with Allure'
  continueOnError: true

- powershell: |
    Write-Host "Downloading Allure..."
    $AllureUrl = "https://github.com/allure-framework/allure2/releases/download/$(ALLURE_VERSION)/allure-$(ALLURE_VERSION).zip"
    Invoke-WebRequest -Uri $AllureUrl -OutFile allure.zip
    Expand-Archive -Path allure.zip -DestinationPath .
    $env:PATH += ";$(Get-Location)\allure-$(ALLURE_VERSION)\bin"
    Write-Host "Generating Allure Report to TestReport..."
    allure generate allure-results --clean -o TestReport
  displayName: 'Generate Allure Report'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'TestReport'
    artifact: 'TestReport'
    publishLocation: 'pipeline'
  displayName: 'Publish TestReport Artifact'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'AzureBlobConnection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Uploading TestReport to $web static site..."
      az storage blob upload-batch \
        --account-name $AZURE_STORAGE_ACCOUNT \
        --account-key $AZURE_STORAGE_KEY \
        --source TestReport \
        --destination '$web' \
        --overwrite
  displayName: 'Upload TestReport to Azure Static Website'
  env:
    AZURE_STORAGE_ACCOUNT: $(AZURE_STORAGE_ACCOUNT)
    AZURE_STORAGE_KEY: $(AZURE_STORAGE_KEY)