base_url: "https://valueinsightpro.jumpiq.com"
login_url: "https://valueinsightpro.jumpiq.com/auth/login"
otp_url: "https://valueinsightpro.jumpiq.com/auth/otp-verify"

timeouts:
  implicit_wait: 5
  explicit_wait: 10
  page_load_timeout: 15

browser:
  default: "chrome"
  headless: true
  window_size: "1920,1080"

# Test Credentials (easily configurable)
credentials:
  valid_user:
    email: "test3"
    password: "value@123"
  invalid_user:
    email: "invalid@example.com"
    password: "WrongPassword"

test_data:
  screenshot_on_failure: true
  report_path: "reports/"
  screenshot_path: "screenshots/" 